#!/usr/bin/perl

my @dvorak_ip = qw/
	127.0.0.1
	::1
	192.168.1.4
	192.168.1.5
	74.43.
	10.0.
	75.17.
	66.44.227.140
	129.21.
/;

my @dvorak_name = qw/
	nevermore
	cheese
	raven
	karl
        pendulum
/;

sub _find_bin_path {
	my ($str) = @_;
	my ($path) = $str =~ /(\S+bin\S+)/;
	return $path;
}

my $hostname;
sub hostname {
	unless (defined $hostname) {
		my $prog = _find_bin_path(`whereis hostname`);
		$hostname = `$prog`;
		chomp $hostname;
	}
	return $hostname;
}

my $ip;
sub ip {
	unless (defined $ip) {
		if (exists $ENV{'SSH_CLIENT'}) {
			($ip) = $ENV{'SSH_CLIENT'} =~ /^(\S+)/;
		}
		else {
			my $cmd = _find_bin_path(`whereis ifconfig`);
			my $result = `$cmd`;
			($ip) = $result =~ 
				/([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})/;
		}
	}
	return $ip;
}

sub found_ip {
	return defined ip;
}

sub ssh {
	return exists $ENV{'SSH_CLIENT'};
}

sub dvorak {
	run('d');
}

sub qwerty {
	run('q');
}

sub run {
	my ($mode) = @_;
	exec "vim.real -S $ENV{'HOME'}/.vimnet/vimrc-$mode " . 
		join(' ', @ARGV);
}

if ((found_ip() && grep { ip() =~ /^\Q$_\E/ } @dvorak_ip) || 
		(!ssh() && grep { hostname() eq $_ } @dvorak_name)) {
	dvorak();
}
else {
	qwerty();
}

